all: heap_radix lim strassen
heap_radix:zhang_xiang_pa2_heap_radix.c
	gcc zhang_xiang_pa2_heap_radix.c -o heap_radix -lm
lim:zhang_xiang_pa2_lim.c
	gcc zhang_xiang_pa2_lim.c -o lim -lm
strassen:zhang_xiang_pa2_strassen.c
	gcc zhang_xiang_pa2_strassen.c -o strassen -lm
clean: 
	rm heap_radix lim strassen

